[package]
name = "zel_core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
iroh = "0.95.1"
log = "0.4.28"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
